package com.biz.dao.auto;

import com.biz.model.auto.Refund;
import com.biz.model.auto.RefundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int countByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int deleteByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int insert(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int insertSelective(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    List<Refund> selectByExampleWithBLOBsWithRowbounds(RefundExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    List<Refund> selectByExampleWithBLOBs(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    List<Refund> selectByExampleWithRowbounds(RefundExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    List<Refund> selectByExample(RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    Refund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") Refund record, @Param("example") RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") Refund record, @Param("example") RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int updateByExample(@Param("record") Refund record, @Param("example") RefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int updateByPrimaryKeySelective(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Mon Oct 10 15:33:29 CST 2016
     */
    int updateByPrimaryKey(Refund record);
}