package com.biz.model.auto;

import java.util.Date;

public class Bill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.open_id
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.account
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private Double account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.use_status
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private Integer useStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.type
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.cate
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private Integer cate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.remark
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.create_date
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.update_date
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.img
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.count
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.open_id
     *
     * @return the value of bill.open_id
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.open_id
     *
     * @param openId the value for bill.open_id
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.account
     *
     * @return the value of bill.account
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public Double getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.account
     *
     * @param account the value for bill.account
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setAccount(Double account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.use_status
     *
     * @return the value of bill.use_status
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.use_status
     *
     * @param useStatus the value for bill.use_status
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.type
     *
     * @return the value of bill.type
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.type
     *
     * @param type the value for bill.type
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.cate
     *
     * @return the value of bill.cate
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public Integer getCate() {
        return cate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.cate
     *
     * @param cate the value for bill.cate
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setCate(Integer cate) {
        this.cate = cate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.remark
     *
     * @return the value of bill.remark
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.remark
     *
     * @param remark the value for bill.remark
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.create_date
     *
     * @return the value of bill.create_date
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.create_date
     *
     * @param createDate the value for bill.create_date
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.update_date
     *
     * @return the value of bill.update_date
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.update_date
     *
     * @param updateDate the value for bill.update_date
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.img
     *
     * @return the value of bill.img
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.img
     *
     * @param img the value for bill.img
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.count
     *
     * @return the value of bill.count
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.count
     *
     * @param count the value for bill.count
     *
     * @mbggenerated Mon Oct 10 15:21:17 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}