package com.biz.model.auto;

public class Cate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cate.id
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cate.use_state
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    private Integer useState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cate.name
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cate.p_id
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    private Integer pId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cate.id
     *
     * @return the value of cate.id
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cate.id
     *
     * @param id the value for cate.id
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cate.use_state
     *
     * @return the value of cate.use_state
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    public Integer getUseState() {
        return useState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cate.use_state
     *
     * @param useState the value for cate.use_state
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    public void setUseState(Integer useState) {
        this.useState = useState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cate.name
     *
     * @return the value of cate.name
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cate.name
     *
     * @param name the value for cate.name
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cate.p_id
     *
     * @return the value of cate.p_id
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cate.p_id
     *
     * @param pId the value for cate.p_id
     *
     * @mbggenerated Sat Oct 08 13:24:09 CST 2016
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }
}