package com.biz.model.auto;

public class House {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.create_person
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.plus_person
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String plusPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house.info
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.id
     *
     * @return the value of house.id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.id
     *
     * @param id the value for house.id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.create_person
     *
     * @return the value of house.create_person
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.create_person
     *
     * @param createPerson the value for house.create_person
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.plus_person
     *
     * @return the value of house.plus_person
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getPlusPerson() {
        return plusPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.plus_person
     *
     * @param plusPerson the value for house.plus_person
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setPlusPerson(String plusPerson) {
        this.plusPerson = plusPerson == null ? null : plusPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house.info
     *
     * @return the value of house.info
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house.info
     *
     * @param info the value for house.info
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}