package com.biz.model.auto;

import java.util.Date;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.open_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.phone
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.nickname
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.headimgurl
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.city
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.province
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.country
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.status
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.create_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.account
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Double account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.update_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.open_id
     *
     * @return the value of person.open_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.open_id
     *
     * @param openId the value for person.open_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.phone
     *
     * @return the value of person.phone
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.phone
     *
     * @param phone the value for person.phone
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.nickname
     *
     * @return the value of person.nickname
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.nickname
     *
     * @param nickname the value for person.nickname
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.headimgurl
     *
     * @return the value of person.headimgurl
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.headimgurl
     *
     * @param headimgurl the value for person.headimgurl
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.city
     *
     * @return the value of person.city
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.city
     *
     * @param city the value for person.city
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.province
     *
     * @return the value of person.province
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.province
     *
     * @param province the value for person.province
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.country
     *
     * @return the value of person.country
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.country
     *
     * @param country the value for person.country
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.status
     *
     * @return the value of person.status
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.status
     *
     * @param status the value for person.status
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.create_date
     *
     * @return the value of person.create_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.create_date
     *
     * @param createDate the value for person.create_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.account
     *
     * @return the value of person.account
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Double getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.account
     *
     * @param account the value for person.account
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setAccount(Double account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.update_date
     *
     * @return the value of person.update_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.update_date
     *
     * @param updateDate the value for person.update_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}