package com.biz.model.auto;

import java.util.Date;

public class Stages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stages.id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stages.open_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stages.refund_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Integer refundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stages.account
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Double account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stages.refund_status
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Integer refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stages.create_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stages.update_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stages.id
     *
     * @return the value of stages.id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stages.id
     *
     * @param id the value for stages.id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stages.open_id
     *
     * @return the value of stages.open_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stages.open_id
     *
     * @param openId the value for stages.open_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stages.refund_id
     *
     * @return the value of stages.refund_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Integer getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stages.refund_id
     *
     * @param refundId the value for stages.refund_id
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setRefundId(Integer refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stages.account
     *
     * @return the value of stages.account
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Double getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stages.account
     *
     * @param account the value for stages.account
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setAccount(Double account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stages.refund_status
     *
     * @return the value of stages.refund_status
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Integer getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stages.refund_status
     *
     * @param refundStatus the value for stages.refund_status
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setRefundStatus(Integer refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stages.create_date
     *
     * @return the value of stages.create_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stages.create_date
     *
     * @param createDate the value for stages.create_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stages.update_date
     *
     * @return the value of stages.update_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stages.update_date
     *
     * @param updateDate the value for stages.update_date
     *
     * @mbggenerated Wed Oct 05 21:48:07 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}